version: "3.8"

services:
  api:
    image: ${DOCKER_USERNAME}/ccgen-api:${TAG:-latest}
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: always
